queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: Site/ClientApp

    verbose: false


- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom

    workingDir: Site/ClientApp

    verbose: false

    customCommand: 'run build'


- task: ArchiveFiles@1
  displayName: 'Archive files'
  inputs:
    rootFolder: Site/ClientApp/build

    includeRootFolder: false

    archiveType: zip


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


